# Generated by Django 4.2.4 on 2023-08-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('telefone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('crm', models.CharField(max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('especialidade', models.CharField(choices=[('Cardiologia', 'Cardiologia'), ('Psiquiatria', 'Psiquiatria'), ('Endocrinologia', 'Endocrinologia'), ('Dermatologia', 'Dermatologia')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('cpf', models.CharField(max_length=20, null=True)),
                ('telefone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Concluída', 'Conluída'), ('Aguardando Exame', 'Aguardando Exame'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], max_length=200, null=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.paciente')),
            ],
        ),
    ]
