# Generated by Django 4.2.4 on 2023-08-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('Concluída', 'Conluída'), ('Aguardando Confirmação', 'Aguardando Confirmação'), ('Aguardando Exames', 'Aguardando Exames'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], max_length=200, null=True),
        ),
    ]
