# Generated by Django 4.2.4 on 2023-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_consulta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateTimeField(null=True),
        ),
    ]
