# Generated by Django 4.2.4 on 2023-08-10 18:15

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_consulta_data_consulta_consulta_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True),
        ),
    ]
