# Generated by Django 4.2.4 on 2023-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
